import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname } from "node:path";
import { fileURLToPath } from "node:url";

const input = fileURLToPath(new URL("../dist/ui/designer.html", import.meta.url));
const output = fileURLToPath(
  new URL("../src/server/generated/designer-html.ts", import.meta.url),
);
const html = await readFile(input, "utf8");
await mkdir(dirname(output), { recursive: true });
await writeFile(
  output,
  `// Generated by scripts/inline-ui.mjs. Do not edit.\nexport const designerHtml = ${JSON.stringify(html)};\n`,
  "utf8",
);
console.log(`Embedded ${html.length.toLocaleString()}-byte app shell into ${output}`);
